### PR TITLE
Add collapsable solution block

### PR DESCRIPTION
**Pull request by chrisburr**
Example:
screen shot 2017-10-18 at 19 54 52

I'm not happy with the formatting of the "Click here to expand" text, suggestions welcome.

### CODE REVIEW

**Comment by chrisburr** [comment]
Also, this makes all blocks collapsable, but the text is only visible if the block is hidden.

**Comment by alexpearce** [comment]
Is this ready for review?

**Comment by chrisburr** [comment]
Yes!

**Comment by alexpearce** [comment]
Looks good; just needs a tweak for better vertical alignment of the toggle text;

```css
.panel-heading h3 span {
    float: right;
    margin-top: 0.5em;
    font-size: 0.7em;
}
```

**Comment by chrisburr** [comment]
Thanks 😄 I think 0.5 is still a little low so I've gone with 0.3, but I can revert it if you disagree.

screen shot 2017-10-25 at 20 07 39

**Comment by alexpearce** [comment]
0.5 looked ok for me, but it is by eye and might vary by OS. Let’s merge this now and tweak later if we think it’s inportant.

**Comment by alexpearce** [comment]
Thanks a lot for the changes, this is a really nice addition to how panels work.

**Comment by henryiii** [comment]
Thanks for adding this! Folding blocks was a key feature used heavily in DevelopKit, and should make the rest of the transition much smoother.

**Comment by henryiii** [comment]
Though I also used an "advanced details" sort of a block, so I might extend this with something similar in a few days.

**Pull request merged**
